/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotallermecanico;

import javax.swing.JOptionPane;

/**
 *
 * @author WALMART
 */
public class JFrameAuto extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAuto
     */
    ListAuto ListAuto=new ListAuto();
    Auto objAuto;
    public JFrameAuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtNombreC = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtFechaE = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opciones = new javax.swing.JMenu();
        Agregar = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        ListaAutomovilesAtender = new javax.swing.JMenuItem();
        ListaAutomovilesAtendidos = new javax.swing.JMenuItem();
        CostoTotal = new javax.swing.JMenuItem();
        ListaAutosRecibidosPorDia = new javax.swing.JMenuItem();
        ListaAutosAtendidosAlDia = new javax.swing.JMenuItem();
        TotalPorTipoDeServicio = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        jLabel3.setText("Nombre Cliente");

        jLabel4.setText("Servicio");

        jLabel5.setText("Costo");

        jLabel6.setText("Fecha Entrada");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        Opciones.setText("Opciones");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        Opciones.add(Agregar);

        jMenuBar1.add(Opciones);

        Consultas.setText("Consultas");

        ListaAutomovilesAtender.setText("Lista Automoviles Atender");
        ListaAutomovilesAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaAutomovilesAtenderActionPerformed(evt);
            }
        });
        Consultas.add(ListaAutomovilesAtender);

        ListaAutomovilesAtendidos.setText("Lista Automoviles Atendidos");
        ListaAutomovilesAtendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaAutomovilesAtendidosActionPerformed(evt);
            }
        });
        Consultas.add(ListaAutomovilesAtendidos);

        CostoTotal.setText("Costo Total Servicios");
        CostoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoTotalActionPerformed(evt);
            }
        });
        Consultas.add(CostoTotal);

        ListaAutosRecibidosPorDia.setText("Lista Autos Recibidos Al dia");
        ListaAutosRecibidosPorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaAutosRecibidosPorDiaActionPerformed(evt);
            }
        });
        Consultas.add(ListaAutosRecibidosPorDia);

        ListaAutosAtendidosAlDia.setText("Lista Autos Atendidos Al Dia");
        ListaAutosAtendidosAlDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaAutosAtendidosAlDiaActionPerformed(evt);
            }
        });
        Consultas.add(ListaAutosAtendidosAlDia);

        TotalPorTipoDeServicio.setText("Total Por Tipos de Servicio");
        TotalPorTipoDeServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPorTipoDeServicioActionPerformed(evt);
            }
        });
        Consultas.add(TotalPorTipoDeServicio);

        jMenuBar1.add(Consultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtModelo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaE, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(txtCosto))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void ListaAutomovilesAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaAutomovilesAtenderActionPerformed
        // TODO add your handling code here:
        txtArea.setText("");
        int tam=ListAuto.size();
        
        for(int x=0;x<tam;x++)
        {
        
        txtArea.append("Marca: " + ListAuto.Mostrar(x).getMarca()+ "\n");
        txtArea.append("Modelo: " + String.valueOf(ListAuto.Mostrar(x).getModelo())+ "\n");
        txtArea.append("Nombre Cliente: " + ListAuto.Mostrar(x).getNombrec()+ "\n");
        txtArea.append("Servicio : " + ListAuto.Mostrar(x).getServicio()+ "\n");
        txtArea.append("Fecha Entrada : " + String.valueOf(ListAuto.Mostrar(x).getFechaE())+ "\n");
        txtArea.append("Costo Servicio : " + String.valueOf(ListAuto.Mostrar(x).getCostoS())+ "\n");
        
        }
       
    }//GEN-LAST:event_ListaAutomovilesAtenderActionPerformed

    private void ListaAutosRecibidosPorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaAutosRecibidosPorDiaActionPerformed
        // TODO add your handling code here:
        long d;
        txtArea.setText("");
        d=Long.parseLong(txtFechaE.getText());
        int v=ListAuto.ListaRecibidosPorDia(d);
        if(v!= -1)
        {
        txtArea.append("Marca: " + ListAuto.Mostrar(v).getMarca()+ "\n");
        txtArea.append("Modelo: " + String.valueOf(ListAuto.Mostrar(v).getModelo())+ "\n");
        txtArea.append("Nombre Cliente: " + ListAuto.Mostrar(v).getNombrec()+ "\n");
        txtArea.append("Servicio : " + ListAuto.Mostrar(v).getServicio()+ "\n");
        txtArea.append("Fecha Entrada : " + String.valueOf(ListAuto.Mostrar(v).getFechaE())+ "\n");
        txtArea.append("Costo Servicio : " + String.valueOf(ListAuto.Mostrar(v).getCostoS())+ "\n");
        }else{
         JOptionPane.showMessageDialog(null,"No hay auto registrado en ese dia");
        }
        
        
    }//GEN-LAST:event_ListaAutosRecibidosPorDiaActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
    int modelo;
    String marca, nombrec, servicio;
    long fechaE;
    float costoS;
    
    modelo=Integer.parseInt(txtModelo.getText());
    marca=txtMarca.getText();
    nombrec=txtNombreC.getText();
    servicio=txtServicio.getText();
    fechaE=Long.parseLong(txtFechaE.getText());
    costoS=Float.parseFloat(txtCosto.getText());
    
    objAuto = new Auto(modelo,marca,nombrec,servicio,fechaE,costoS);
    objAuto.setModelo(modelo);
    objAuto.setMarca(marca);
    objAuto.setNombrec(nombrec);
    objAuto.setFechaE(fechaE);
    objAuto.setServicio(servicio);
    objAuto.setCostoS(costoS);
    
    ListAuto.Agregar(objAuto);
    txtFechaE.setText("");
    txtArea.setText("");
    txtMarca.setText("");
    txtModelo.setText("");
    txtNombreC.setText("");
    txtServicio.setText("");
    txtCosto.setText("");
    
    }//GEN-LAST:event_AgregarActionPerformed

    private void ListaAutomovilesAtendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaAutomovilesAtendidosActionPerformed
        // TODO add your handling code here:
     txtArea.setText("");
     
     int msj=JOptionPane.showConfirmDialog(null,"Desea Reparar Auto");
    
     if(msj==JOptionPane.YES_OPTION)
     {
     //long fechaS=Long.parseLong(JOptionPane.showInputDialog("Ingresar Fecha Salida"));
     ListAuto.Atendidos();
     int tam=ListAuto.sizeAtendidos();
     
     for(int x=0;x<tam;x++)
     {
        txtArea.append("Marca: " + ListAuto.getListaAtendidos(x).getMarca()+ "\n");
        txtArea.append("Modelo: " + String.valueOf(ListAuto.getListaAtendidos(x).getModelo())+ "\n");
        txtArea.append("Nombre Cliente: " + ListAuto.getListaAtendidos(x).getNombrec()+ "\n");
        txtArea.append("Servicio : " + ListAuto.getListaAtendidos(x).getServicio()+ "\n");
        txtArea.append("Fecha Entrada : " + String.valueOf(ListAuto.getListaAtendidos(x).getFechaE())+ "\n");
        txtArea.append("Costo Servicio : " + String.valueOf(ListAuto.getListaAtendidos(x).getCostoS())+ "\n");
        //txtArea.append("Fecha de Salida: " + fechaS + "\n");
     }
     }
     if(msj==JOptionPane.NO_OPTION)
     {
     JOptionPane.showMessageDialog(null,"No se reparo Auto");
     }
     if(msj==JOptionPane.CANCEL_OPTION)
     {
     JOptionPane.showMessageDialog(null,"Cancelar Opcion");
     }
     
        
    }//GEN-LAST:event_ListaAutomovilesAtendidosActionPerformed

    private void CostoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoTotalActionPerformed
        // TODO add your handling code here:
        float total=0;
        total=ListAuto.TotalServicio();
        
        txtArea.append("Total de servicio: " + total );
    }//GEN-LAST:event_CostoTotalActionPerformed

    private void ListaAutosAtendidosAlDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaAutosAtendidosAlDiaActionPerformed
        // TODO add your handling code here:
        long d;
        txtArea.setText("");
        d=Long.parseLong(txtFechaE.getText());
        int v=ListAuto.ListaAtendidosPorDia(d);
        if(v!= -1)
        {
        txtArea.append("Marca: " + ListAuto.getListaAtendidos(v).getMarca()+ "\n");
        txtArea.append("Modelo: " + String.valueOf(ListAuto.getListaAtendidos(v).getModelo())+ "\n");
        txtArea.append("Nombre Cliente: " + ListAuto.getListaAtendidos(v).getNombrec()+ "\n");
        txtArea.append("Servicio : " + ListAuto.getListaAtendidos(v).getServicio()+ "\n");
        txtArea.append("Fecha Entrada : " + String.valueOf(ListAuto.getListaAtendidos(v).getFechaE())+ "\n");
        txtArea.append("Costo Servicio : " + String.valueOf(ListAuto.getListaAtendidos(v).getCostoS())+ "\n");
        }else{
         JOptionPane.showMessageDialog(null,"No hay auto registrado en ese dia");
        }

    }//GEN-LAST:event_ListaAutosAtendidosAlDiaActionPerformed

    private void TotalPorTipoDeServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPorTipoDeServicioActionPerformed
        // TODO add your handling code here:
        txtArea.setText("");
        String ser;
        float total;
        ser=txtServicio.getText();
        total=ListAuto.TotalPorTipodeServicio(ser);
        
        txtArea.append("Nombre del servicio: " + ser +"\n" + "total de servicios: " + total );
        
        
    }//GEN-LAST:event_TotalPorTipoDeServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenuItem CostoTotal;
    private javax.swing.JMenuItem ListaAutomovilesAtender;
    private javax.swing.JMenuItem ListaAutomovilesAtendidos;
    private javax.swing.JMenuItem ListaAutosAtendidosAlDia;
    private javax.swing.JMenuItem ListaAutosRecibidosPorDia;
    private javax.swing.JMenu Opciones;
    private javax.swing.JMenuItem TotalPorTipoDeServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFechaE;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
